name: Creation

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: 'true'
      - name: Create Artifact
        run: |
          test="test"
          echo $test > test.txt
